[package]
name = "rust_bitcoin_safety"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
itertools = "0.10.5"
ripemd = "0.1.3"
secp256k1 = "0.27.0"
sha256 = "1.1.3"
